    selenium-hub:
      image: selenium/hub
      ports:
        - 4444:4444

    node-chrome:
      image: selenium/node-chrome
#      image: selenium/node-chrome-debug
      ports:
        - 5900
      links:
        - selenium-hub:hub
      environment:
        - DBUS_SESSION_BUS_ADDRESS=/dev/null
      volumes:
        - /dev/shm:/dev/shm
        - ./integration-data:/integration-data

#    node-firefox:
#      image: selenium/node-firefox
##      image: selenium/node-firefox-debug
##      image: selenium/node-firefox:45.0.2
#      ports:
#        - 5900
#      links:
#        - selenium-hub:hub
#      environment:
#        - DBUS_SESSION_BUS_ADDRESS=/dev/null
#      volumes:
#        - ./integration-data:/integration-data

